version: '3'

volumes:
  postgres_data:
      driver: local

services:
  goproxy:
      build: ..
      ports:
        - 2000:8080

  echo:
      image: hashicorp/http-echo
      ports:
        - 5678:5678
      command: ["-text", "echo server response"]

  postgres:
      image: postgres:12.1
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password

  keycloak:
      image: jboss/keycloak:8.0.1
      volumes:
        - ./keycloak-data:/opt/jboss/keycloak/imports
      command: 
        - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: pass
        PROXY_ADDRESS_FORWARDING: 'true'
      ports:
        - 8080
      depends_on:
        - postgres
